# Assignment 3.1  Project 3
### Name _____________  
Date ____________ 
Course _________                            
# Many questions are answered; for the remaining replace each ??? by your answer


# Outcomes: 
* Loading multiple files into "pandas" DataFras from a hierarchical directory.me
* Combining "pandas" DataFrames
* Sing combinedve tables aa s single file


# Motivating Problem

* Process trajectory data recorded as GPS trace
* Real data sets recorded by people carryiPGPS-S enabled devices
* Data available over multiple years for people traveling in different modes like walking, ridinthe bus,us etc.
The mostst important part othe f data ithe s latitudeand , longitude sequence with timestamp for each pair (forms trajectory data)
* Severaexcitingng problems in Activity Monitoring are naturally related to such data sets  
* Data taken from the freely available Microsoft Geolife data set https://www.microsoft.com/en-us/download/details.aspx?id=52367 
* A smaller data set named Geolife_Trajectories_1.3.zip is provided along with this notebook
    * This data set has data fofive 5 users ouof t 182 users in thcompletell data set
    * The five users are numbered 000, 036, 037, 120 and 121
* That file must be uncompressed within the same folder that has this notebook

# Task 1 - Review of Project 1

### General Information:
* As you remember from Module 1 - Task 1, very often we need to import additional programs that are organized into various libraries.
* As you remember from Module 1 - Task 2, the directory structure is in the form of a tree as you know from your experience in the windows environment.
* To uniquely identify a file, we provide a path that is the concatenation of all tree node names leading to the file.
* As you remember from Module 1 - Task 3, many libraries have functions that we can invoke during code writing.


### Specific Information:
* "pandas" is an example of such library in Python environment such as the Jupyter notebook
* The "pandas" library is a set of programs for efficient processing of big tabular data 
* One important function in the "pandas" libary is "read_csv()"

In [1]:
import numpy
import pandas as pd  #imports the "pandas" library
import os

In [2]:
# code repeated from Project 1

# creating DataFrame 'Points_User121_File1
fileName1 = '20091004095125.csv' # we pick one out of the two files for this user
path1 = './Geolife_Trajectories_1.3/data/121/Trajectory/' #path to the file
FileIdentification1 = path1 + fileName1 #File Identification by concatenating path with file name
# creating DataFrame 'Points_User121_File1'
Points_User121_File1 = pd.read_csv(FileIdentification1)
Points_User121_File1

,Order,Latitude,Longitude,Unused,Altitude,Days,Date,Time
0,0,39.175229,117.150620,0,492.335292,40090.410764,2009-10-04,09:51:30
1,1,39.175153,117.150866,0,492.761617,40090.410822,2009-10-04,09:51:35
2,2,39.175149,117.150966,0,494.147372,40090.410880,2009-10-04,09:51:40
3,3,39.175126,117.150976,0,494.922628,40090.410937,2009-10-04,09:51:45
4,4,39.175124,117.150961,0,494.743156,40090.410995,2009-10-04,09:51:50
...,...,...,...,...,...,...,...,...
1162,1162,39.191409,117.108870,0,-10.511834,40090.498889,2009-10-04,11:58:24
1163,1163,39.191447,117.108848,0,-9.337103,40090.498947,2009-10-04,11:58:29
1164,1164,39.191479,117.108839,0,-8.545226,40090.499005,2009-10-04,11:58:34
1165,1165,39.191482,117.108824,0,-8.590262,40090.499062,2009-10-04,11:58:39
1166,1166,39.191486,117.108811,0,-8.612119,40090.499120,2009-10-04,11:58:44

In [3]:
# Will read  file2 
fileName2 = '20091005102823.csv' # we pick second out of the files for this user
path1 = './Geolife_Trajectories_1.3/data/121/Trajectory/' #path to the file
FileIdentification2 = path1 + fileName2 #File Identification by concatenating path with file name
# creating DataFrame 'Points_User121_File1'
Points_User121_File2 = pd.read_csv(FileIdentification2)
Points_User121_File2

,Order,Latitude,Longitude,Unused,Altitude,Days,Date,Time
0,0,39.180741,117.143490,0,492.081982,40091.436435,2009-10-05,10:28:28
1,1,39.180634,117.143428,0,491.801283,40091.436493,2009-10-05,10:28:33
2,2,39.180551,117.143343,0,490.351749,40091.436551,2009-10-05,10:28:38
3,3,39.180478,117.143261,0,488.202152,40091.436609,2009-10-05,10:28:43
4,4,39.180337,117.143144,0,486.045495,40091.436667,2009-10-05,10:28:48
...,...,...,...,...,...,...,...,...
564,564,39.181190,117.143998,0,56.275446,40091.499097,2009-10-05,11:58:42
565,565,39.181147,117.144037,0,53.142851,40091.499155,2009-10-05,11:58:47
566,566,39.181153,117.144059,0,48.520302,40091.499213,2009-10-05,11:58:52
567,567,39.181115,117.144096,0,47.643996,40091.499271,2009-10-05,11:58:57
568,568,39.181031,117.144189,0,51.638885,40091.499329,2009-10-05,11:59:02

#### Apply in typical situations:
1.1. Write the code to load the first two files for user 120 into new dataframes called Points_User120_File1 and Points_User120_File2

In [4]:
# ???

# Task 2:  Concatenating  Two DataFrames - Union Operation

### General Information:
* Concatenating means combining two DataFrames into a single DataFrame. 
* In general there are cases of simple and complex concatenation. 
* Simple concatenation is when there is a smooth transition between the last item in the first file and the first item of the second file. 
* Complex concatenation is when a special technique needs to be applied.

There are several techniques to accomplish complex concatentation:
1. Use additional column with the file name since the file name uniquly identifes sub-directory.
2. Use additional row to indicate the sentinel
3. Use double indexing to provide a global index and local within trajectory index.

### Specific Information:
* The last item in the file  designates the end of sub-trajectory and the beginning of the new file can  represent the begining of completely new sub-directory with the space and time  jump hard to interpret.
* This transition can polute any statistics about time and speed of travel.  In the code below we have used the last method for several reasons: 
    * we could use regular concatenate plus minor modifications
    * our files are heavily indexed anyway since our processing requires indexing for speed
    * for Big Data we can save space without additional attribute
    * indexes are more understandable to humans for visual inspections
* In our case  combining Points_User121_File1 and Points_User121_File1 will result in a single DataFrame, Points_User121.
* It can be accomplished by the following code:

In [5]:
# Load data for a single trajectory for a specific user and display the first rows 
Points_User121 = pd.concat([Points_User121_File1, Points_User121_File2], ignore_index=True)
Points_User121

,Order,Latitude,Longitude,Unused,Altitude,Days,Date,Time
0,0,39.175229,117.150620,0,492.335292,40090.410764,2009-10-04,09:51:30
1,1,39.175153,117.150866,0,492.761617,40090.410822,2009-10-04,09:51:35
2,2,39.175149,117.150966,0,494.147372,40090.410880,2009-10-04,09:51:40
3,3,39.175126,117.150976,0,494.922628,40090.410937,2009-10-04,09:51:45
4,4,39.175124,117.150961,0,494.743156,40090.410995,2009-10-04,09:51:50
...,...,...,...,...,...,...,...,...
1731,564,39.181190,117.143998,0,56.275446,40091.499097,2009-10-05,11:58:42
1732,565,39.181147,117.144037,0,53.142851,40091.499155,2009-10-05,11:58:47
1733,566,39.181153,117.144059,0,48.520302,40091.499213,2009-10-05,11:58:52
1734,567,39.181115,117.144096,0,47.643996,40091.499271,2009-10-05,11:58:57
1735,568,39.181031,117.144189,0,51.638885,40091.499329,2009-10-05,11:59:02

### Task 2 Questions and Problems

#### Output Understanding:

2.1. The Order column was the index supplied by the original file. Is it necessary to have 2 indexes as above to identify specific GPS measurements?

Yes. The order index indicates the GPS measurements index for the specific file.
______________________________

#### Concept Understanding:

2.2. Why is the ignore index parameter set to True?

So we may have a new global index for the new dataframe that will have all values of both concatenated dataframes. 
______________________________

#### Code Understanding: 

2.3. What panda operator was used to combine the two files into a single DataFrame?

concat()
______________________________

#### Apply in typical situations:

2.4. What happens if you were to run the code without ignore_index=True?

The indices in the left column will match the numbers in the Order column
______________________________

2.5 Write a code by copying the code in Task 3 above, but remove "ignore_index=True", and use the dataframes created from user 121

In [6]:
# code for task 2.5
Points_User121A = pd.concat([Points_User121_File1, Points_User121_File2])
Points_User121A

,Order,Latitude,Longitude,Unused,Altitude,Days,Date,Time
0,0,39.175229,117.150620,0,492.335292,40090.410764,2009-10-04,09:51:30
1,1,39.175153,117.150866,0,492.761617,40090.410822,2009-10-04,09:51:35
2,2,39.175149,117.150966,0,494.147372,40090.410880,2009-10-04,09:51:40
3,3,39.175126,117.150976,0,494.922628,40090.410937,2009-10-04,09:51:45
4,4,39.175124,117.150961,0,494.743156,40090.410995,2009-10-04,09:51:50
...,...,...,...,...,...,...,...,...
564,564,39.181190,117.143998,0,56.275446,40091.499097,2009-10-05,11:58:42
565,565,39.181147,117.144037,0,53.142851,40091.499155,2009-10-05,11:58:47
566,566,39.181153,117.144059,0,48.520302,40091.499213,2009-10-05,11:58:52
567,567,39.181115,117.144096,0,47.643996,40091.499271,2009-10-05,11:58:57
568,568,39.181031,117.144189,0,51.638885,40091.499329,2009-10-05,11:59:02

2.6. Write a code to create a new table Points_User120 from the concatenation of the first data frames for user 120  
and print Points_User120

In [7]:
# ???

2.7. Which DataFrame is larger: Points_User120 or Points_User121?

* ???
______________________________

### General Information:
* Writing a function to do all of our work is much more efficient than trying to do everything manually
* It can save on memory, too, since python cleans up memory after the function finishes.


### Specific Information:
* In our specific case, we will define a function that will concatenate two dataframes
* When we call the function, it will load both Dataframes and cocnatenate them together into a new DataFrame
* It will return that DataFrame to us, allowing us to preserve it in a new variable name.

### Define a Function Implementation for Task 2
* run the code

In [8]:
def combineTables(Table1, Table2):
    newTable = pd.concat([Table1, Table2], ignore_index=True)
    return(newTable)

In [9]:
PointsTable_User121 = combineTables(Points_User121_File1, Points_User121_File2)
Points_User121

,Order,Latitude,Longitude,Unused,Altitude,Days,Date,Time
0,0,39.175229,117.150620,0,492.335292,40090.410764,2009-10-04,09:51:30
1,1,39.175153,117.150866,0,492.761617,40090.410822,2009-10-04,09:51:35
2,2,39.175149,117.150966,0,494.147372,40090.410880,2009-10-04,09:51:40
3,3,39.175126,117.150976,0,494.922628,40090.410937,2009-10-04,09:51:45
4,4,39.175124,117.150961,0,494.743156,40090.410995,2009-10-04,09:51:50
...,...,...,...,...,...,...,...,...
1731,564,39.181190,117.143998,0,56.275446,40091.499097,2009-10-05,11:58:42
1732,565,39.181147,117.144037,0,53.142851,40091.499155,2009-10-05,11:58:47
1733,566,39.181153,117.144059,0,48.520302,40091.499213,2009-10-05,11:58:52
1734,567,39.181115,117.144096,0,47.643996,40091.499271,2009-10-05,11:58:57
1735,568,39.181031,117.144189,0,51.638885,40091.499329,2009-10-05,11:59:02

#### Apply in typical situations:
2.8. Write the code  to redefine Points_User120 using function 'combineTables()' with the first dataframes for user 120.

In [10]:
# ???

# Task 3:  Reading and Concatenating multiple files in the given Directory

### General:
* When we have to read data from many files, assigning each file to a different variable is obviously not efficient and a loop should be used.

### Specific:
* Let us first do a preparatory exercise to identify file names in the given Directory i.e in the directory corresponding to user 121
* We will use the 'os' library command  called 'listdir()' to create a list of file names in the given Directory
* In our case we want to make sure to find only files ending with 'csv' string. 
* We use an 'if' statement to identify these files. 
* There are many various string commands that you can use  e.g. 'endswith()'

In [11]:
userId='121'
dataPath = './Geolife_Trajectories_1.3/data/' + userId + '/Trajectory'
count = 0
print('File names of the csv type in the directory called ' + userId + ':')
for file in os.listdir(dataPath):
    if file.lower().endswith(".csv"):
        print("csv file:", file)
        count += 1
        
print("Number of eligible files:", count)
print("Total number of files:", len(os.listdir(dataPath)))

File names of the csv type in the directory called 121:
csv file: 20091004095125.csv
csv file: 20091005102823.csv
csv file: 20091008154408.csv
csv file: 20091009204618.csv
csv file: 20091011115337.csv
Number of eligible files: 5
Total number of files: 5

### Task 3 Questions  and Problems

#### Output Understanding:

3.1. Was the total number of files correct?

???
______________________________

#### Concept Understanding:

3.2. Open up a file manager window in Windows and navigate to './Geolife_Trajectories_1.3/data/121/Trajectory'. How many files do you see in this directory? Was your output correct?

???
______________________________

#### Code Understanding: 

3.3. What would happen if we remove line 7 in the code above?

We would still see the total number of files, but the filenames in the output would be missing.
______________________________

#### Apply in typical situations:

3.4. Why is  it  a good idea to select only the files of given type (comply with the process of verifying and cleaning data)?

If we run across a file that our program cannot handle, it might crash or do something unexpected.
______________________________

Consider a function "investigateTree()" using the following directory 
* './Geolife_Trajectories_1.3/data/'

In [12]:
# code for task 3.5
def investigateTree():
    dataPath = './Geolife_Trajectories_1.3/data/'
    count  = 0
    print('File names of the csv type in the tree called ' + dataPath + ':')
    for file in os.listdir(dataPath):
        if file.lower().endswith(".csv"):
            print("csv file:", file)
            count += 1
    print("Number of eligible files:", count)
    print("Total number of files:", len(os.listdir(dataPath)))

In [13]:
investigateTree()

File names of the csv type in the tree called ./Geolife_Trajectories_1.3/data/:
Number of eligible files: 0
Total number of files: 5



3.5. Use  your code from 3.5, modify the function to accepts UserID as a parameter to search specific path directory calling the function investigateUser(UserId)
* Verify function by Using User 121
* Next, use the function for user 037

In [14]:
# code for task 3.6
def investigateUser(UserId):
    # Will accept UserId as int then convert into string for process
    dataPath = './Geolife_Trajectories_1.3/data/' + str(UserId) + '/Trajectory'
    count  = 0
    print('File names of the csv type in the directory called ' + str(UserId) + ':')
    for file in os.listdir(dataPath):
        if file.lower().endswith(".csv"):
            print("csv file:", file)
            count += 1
    print("Number of eligible files:", count)
    print("Total number of files:", len(os.listdir(dataPath)))

In [15]:
investigateUser(121)

File names of the csv type in the directory called 121:
csv file: 20091004095125.csv
csv file: 20091005102823.csv
csv file: 20091008154408.csv
csv file: 20091009204618.csv
csv file: 20091011115337.csv
Number of eligible files: 5
Total number of files: 5

In [16]:
# ???

### General Information:
* The code for Identifying  file names in the given Directory can be extended for Creating a User define Function for Reading and Concatenating multiple files in the given Directory 

### Specific Information:
* In our specific case, we will define a function that will read in the csv files for a given directory
* It will also add these files into a final DataFrame
* At the end, it will return that DataFrame to us, allowing us to preserve it in a new variable name.

In [17]:
def readDataFromDirectory(userId):
    dataPath = './Geolife_Trajectories_1.3/data/' + userId + '/Trajectory'
    print('dataPath:', dataPath)
    print()
    table = pd.DataFrame() #create an empty table
    for file in os.listdir(dataPath):
        if file.lower().endswith(".csv"): # only work with csv files, because other file types would crash program
            print("csv file:", file)
            FileIdentification = dataPath +'/'+ file
            print('FileIdentification:',FileIdentification)
            tempTable = pd.read_csv(FileIdentification) # fill temporary table with data from new file
            table = pd.concat([table, tempTable], ignore_index=True) # concatenate final with temp, in a loop.
            print("Added", file, "to table")
            print()
    print()
    return(table)

In [18]:
# function call
userId='120'
Points_User120 = readDataFromDirectory(userId) 
Points_User120

dataPath: ./Geolife_Trajectories_1.3/data/120/Trajectory

csv file: 20090919071137.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/120/Trajectory/20090919071137.csv
Added 20090919071137.csv to table

csv file: 20090920065901.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/120/Trajectory/20090920065901.csv
Added 20090920065901.csv to table

,Order,Latitude,Longitude,Unused,Altitude,Days,Date,Time
0,0,39.982380,116.320448,0,0,40075.299861,2009-09-19,07:11:48
1,1,39.982380,116.320455,0,0,40075.299884,2009-09-19,07:11:50
2,2,39.982397,116.320455,0,0,40075.299907,2009-09-19,07:11:52
3,3,39.982425,116.320460,0,0,40075.299931,2009-09-19,07:11:54
4,4,39.982458,116.320463,0,0,40075.299954,2009-09-19,07:11:56
...,...,...,...,...,...,...,...,...
10783,2566,42.521328,117.231613,0,0,40076.424711,2009-09-20,10:11:35
10784,2567,42.521300,117.231615,0,0,40076.424734,2009-09-20,10:11:37
10785,2568,42.521260,117.231617,0,0,40076.424757,2009-09-20,10:11:39
10786,2569,42.521357,117.231460,0,0,40076.431238,2009-09-20,10:20:59
10787,2570,42.521357,117.231460,0,0,40076.431238,2009-09-20,10:20:59

### Task 3 Continuation Questions  and Problems

#### Output Understanding:

3.7. Why is it important to print out each csv file, the data path,and "added to new table"?

This shows where the data is coming from and the order the data files are added as well.
______________________________

### Concept Understanding:

3.8. How can we improve this function defintion?

The current function will have to be called for each user in the directory (5x for USERS: 000, 036,037, 120, 121). We prefer one call.
______________________________

#### Code Understanding: 

3.9. Is the length of rows equal to previous concatenated "PointsTable_User120"? Why or why not?
 
???
______________________________

#### Apply in typical situations:

3.10. Change the userId to 121 and create a new table
call the new table PointsTable_User121

In [19]:
# code for task 3.10

# Task 4: Reading files from Multiple Directories and adding appropriate subdirectory identifiers

### General Information:

* The Path provides a directory of files to add to a table to be more efficient by using the os library.

### Specific Information:

* Use the os method listdir(path)- to get the list of directories of the path
* This will be the Users
* From Task 3 update the code using the proper os methods.

In [20]:
def readDataFromDirectories(path='./Geolife_Trajectories_1.3/Data/'):
    table = pd.DataFrame()
    for dir in os.listdir(path):
        print("Adding user", dir, "to table")
        tempTable = readDataFromDirectory(dir)
        tempTable['User']= str(dir) # to add the username for this directory
        table = pd.concat([table, tempTable], ignore_index=True)
    print()
    return table

In [21]:
Points_All3 = readDataFromDirectories()
Points_All3

Adding user 000 to table
dataPath: ./Geolife_Trajectories_1.3/data/000/Trajectory

csv file: 20081023025304.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081023025304.csv
Added 20081023025304.csv to table

csv file: 20081024020959.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081024020959.csv
Added 20081024020959.csv to table

csv file: 20081026134407.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081026134407.csv
Added 20081026134407.csv to table

csv file: 20081027115449.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081027115449.csv
Added 20081027115449.csv to table

csv file: 20081028003826.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081028003826.csv
Added 20081028003826.csv to table

csv file: 20081029092138.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081029092138.csv
Added 20081029092138.csv to table

csv file: 20081029093038.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081029093038.csv
Added 20081029093038.csv to table

csv file: 20081103101336.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081103101336.csv
Added 20081103101336.csv to table

csv file: 20081103232153.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081103232153.csv
Added 20081103232153.csv to table

csv file: 20081110013637.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081110013637.csv
Added 20081110013637.csv to table

csv file: 20081111001704.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081111001704.csv
Added 20081111001704.csv to table

csv file: 20081112023003.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081112023003.csv
Added 20081112023003.csv to table

csv file: 20081112091400.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081112091400.csv
Added 20081112091400.csv to table

csv file: 20081113034608.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081113034608.csv
Added 20081113034608.csv to table

csv file: 20081114015255.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081114015255.csv
Added 20081114015255.csv to table

csv file: 20081114101436.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081114101436.csv
Added 20081114101436.csv to table

csv file: 20081115010133.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081115010133.csv
Added 20081115010133.csv to table

csv file: 20081116085532.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081116085532.csv
Added 20081116085532.csv to table

csv file: 20081117051133.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081117051133.csv
Added 20081117051133.csv to table

csv file: 20081117155223.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081117155223.csv
Added 20081117155223.csv to table

csv file: 20081118095005.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081118095005.csv
Added 20081118095005.csv to table

csv file: 20081118095400.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081118095400.csv
Added 20081118095400.csv to table

csv file: 20081118162008.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081118162008.csv
Added 20081118162008.csv to table

csv file: 20081119012806.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081119012806.csv
Added 20081119012806.csv to table

csv file: 20081119112035.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081119112035.csv
Added 20081119112035.csv to table

csv file: 20081120035736.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081120035736.csv
Added 20081120035736.csv to table

csv file: 20081121040936.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081121040936.csv
Added 20081121040936.csv to table

csv file: 20081121113038.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081121113038.csv
Added 20081121113038.csv to table

csv file: 20081122012309.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081122012309.csv
Added 20081122012309.csv to table

csv file: 20081123102153.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081123102153.csv
Added 20081123102153.csv to table

csv file: 20081201111827.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081201111827.csv
Added 20081201111827.csv to table

csv file: 20081202071136.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081202071136.csv
Added 20081202071136.csv to table

csv file: 20081202071531.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081202071531.csv
Added 20081202071531.csv to table

csv file: 20081203032326.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081203032326.csv
Added 20081203032326.csv to table

csv file: 20081203151206.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081203151206.csv
Added 20081203151206.csv to table

csv file: 20081203234939.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081203234939.csv
Added 20081203234939.csv to table

csv file: 20081210023503.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081210023503.csv
Added 20081210023503.csv to table

csv file: 20081211044624.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081211044624.csv
Added 20081211044624.csv to table

csv file: 20081211121432.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081211121432.csv
Added 20081211121432.csv to table

csv file: 20081212042525.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081212042525.csv
Added 20081212042525.csv to table

csv file: 20081212101236.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081212101236.csv
Added 20081212101236.csv to table

csv file: 20081214011036.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20081214011036.csv
Added 20081214011036.csv to table

csv file: 20090330005208.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090330005208.csv
Added 20090330005208.csv to table

csv file: 20090331003904.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090331003904.csv
Added 20090331003904.csv to table

csv file: 20090401050607.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090401050607.csv
Added 20090401050607.csv to table

csv file: 20090401202331.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090401202331.csv
Added 20090401202331.csv to table

csv file: 20090402060732.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090402060732.csv
Added 20090402060732.csv to table

csv file: 20090403011657.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090403011657.csv
Added 20090403011657.csv to table

csv file: 20090405051938.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090405051938.csv
Added 20090405051938.csv to table

csv file: 20090406023702.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090406023702.csv
Added 20090406023702.csv to table

csv file: 20090409182800.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090409182800.csv
Added 20090409182800.csv to table

csv file: 20090410021935.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090410021935.csv
Added 20090410021935.csv to table

csv file: 20090411052358.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090411052358.csv
Added 20090411052358.csv to table

csv file: 20090412004905.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090412004905.csv
Added 20090412004905.csv to table

csv file: 20090412073303.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090412073303.csv
Added 20090412073303.csv to table

csv file: 20090413050806.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090413050806.csv
Added 20090413050806.csv to table

csv file: 20090413144632.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090413144632.csv
Added 20090413144632.csv to table

csv file: 20090413213935.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090413213935.csv
Added 20090413213935.csv to table

csv file: 20090415000406.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090415000406.csv
Added 20090415000406.csv to table

csv file: 20090415074008.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090415074008.csv
Added 20090415074008.csv to table

csv file: 20090416002705.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090416002705.csv
Added 20090416002705.csv to table

csv file: 20090417002430.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090417002430.csv
Added 20090417002430.csv to table

csv file: 20090418172238.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090418172238.csv
Added 20090418172238.csv to table

csv file: 20090419005226.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090419005226.csv
Added 20090419005226.csv to table

csv file: 20090419175500.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090419175500.csv
Added 20090419175500.csv to table

csv file: 20090420013034.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090420013034.csv
Added 20090420013034.csv to table

csv file: 20090420235106.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090420235106.csv
Added 20090420235106.csv to table

csv file: 20090422023859.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090422023859.csv
Added 20090422023859.csv to table

csv file: 20090422203607.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090422203607.csv
Added 20090422203607.csv to table

csv file: 20090423092838.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090423092838.csv
Added 20090423092838.csv to table

csv file: 20090423181101.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090423181101.csv
Added 20090423181101.csv to table

csv file: 20090424004737.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090424004737.csv
Added 20090424004737.csv to table

csv file: 20090424171137.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090424171137.csv
Added 20090424171137.csv to table

csv file: 20090425005731.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090425005731.csv
Added 20090425005731.csv to table

csv file: 20090426025714.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090426025714.csv
Added 20090426025714.csv to table

csv file: 20090426175513.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090426175513.csv
Added 20090426175513.csv to table

csv file: 20090427010230.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090427010230.csv
Added 20090427010230.csv to table

csv file: 20090427215826.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090427215826.csv
Added 20090427215826.csv to table

csv file: 20090428051631.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090428051631.csv
Added 20090428051631.csv to table

csv file: 20090429005954.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090429005954.csv
Added 20090429005954.csv to table

csv file: 20090430032332.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090430032332.csv
Added 20090430032332.csv to table

csv file: 20090501035138.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090501035138.csv
Added 20090501035138.csv to table

csv file: 20090502074907.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090502074907.csv
Added 20090502074907.csv to table

csv file: 20090503033926.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090503033926.csv
Added 20090503033926.csv to table

csv file: 20090504023301.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090504023301.csv
Added 20090504023301.csv to table

csv file: 20090504203925.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090504203925.csv
Added 20090504203925.csv to table

csv file: 20090505032432.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090505032432.csv
Added 20090505032432.csv to table

csv file: 20090505195337.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090505195337.csv
Added 20090505195337.csv to table

csv file: 20090506125906.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090506125906.csv
Added 20090506125906.csv to table

csv file: 20090507024201.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090507024201.csv
Added 20090507024201.csv to table

csv file: 20090507192952.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090507192952.csv
Added 20090507192952.csv to table

csv file: 20090508015405.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090508015405.csv
Added 20090508015405.csv to table

csv file: 20090508100431.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090508100431.csv
Added 20090508100431.csv to table

csv file: 20090509050136.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090509050136.csv
Added 20090509050136.csv to table

csv file: 20090509181636.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090509181636.csv
Added 20090509181636.csv to table

csv file: 20090510020206.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090510020206.csv
Added 20090510020206.csv to table

csv file: 20090510222007.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090510222007.csv
Added 20090510222007.csv to table

csv file: 20090511064136.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090511064136.csv
Added 20090511064136.csv to table

csv file: 20090511174427.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090511174427.csv
Added 20090511174427.csv to table

csv file: 20090512013109.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090512013109.csv
Added 20090512013109.csv to table

csv file: 20090512195558.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090512195558.csv
Added 20090512195558.csv to table

csv file: 20090513054336.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090513054336.csv
Added 20090513054336.csv to table

csv file: 20090514015425.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090514015425.csv
Added 20090514015425.csv to table

csv file: 20090515014004.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090515014004.csv
Added 20090515014004.csv to table

csv file: 20090516091038.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090516091038.csv
Added 20090516091038.csv to table

csv file: 20090517054624.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090517054624.csv
Added 20090517054624.csv to table

csv file: 20090517220626.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090517220626.csv
Added 20090517220626.csv to table

csv file: 20090518064638.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090518064638.csv
Added 20090518064638.csv to table

csv file: 20090519094537.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090519094537.csv
Added 20090519094537.csv to table

csv file: 20090519174038.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090519174038.csv
Added 20090519174038.csv to table

csv file: 20090520010901.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090520010901.csv
Added 20090520010901.csv to table

csv file: 20090520125535.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090520125535.csv
Added 20090520125535.csv to table

csv file: 20090520210235.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090520210235.csv
Added 20090520210235.csv to table

csv file: 20090521045307.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090521045307.csv
Added 20090521045307.csv to table

csv file: 20090521231053.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090521231053.csv
Added 20090521231053.csv to table

csv file: 20090522094234.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090522094234.csv
Added 20090522094234.csv to table

csv file: 20090523011253.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090523011253.csv
Added 20090523011253.csv to table

csv file: 20090524094557.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090524094557.csv
Added 20090524094557.csv to table

csv file: 20090524215455.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090524215455.csv
Added 20090524215455.csv to table

csv file: 20090525093647.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090525093647.csv
Added 20090525093647.csv to table

csv file: 20090526040256.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090526040256.csv
Added 20090526040256.csv to table

csv file: 20090526170706.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090526170706.csv
Added 20090526170706.csv to table

csv file: 20090527080105.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090527080105.csv
Added 20090527080105.csv to table

csv file: 20090528012338.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090528012338.csv
Added 20090528012338.csv to table

csv file: 20090530034445.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090530034445.csv
Added 20090530034445.csv to table

csv file: 20090531031407.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090531031407.csv
Added 20090531031407.csv to table

csv file: 20090531192301.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090531192301.csv
Added 20090531192301.csv to table

csv file: 20090601082932.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090601082932.csv
Added 20090601082932.csv to table

csv file: 20090602035536.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090602035536.csv
Added 20090602035536.csv to table

csv file: 20090602185307.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090602185307.csv
Added 20090602185307.csv to table

csv file: 20090603064302.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090603064302.csv
Added 20090603064302.csv to table

csv file: 20090604053730.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090604053730.csv
Added 20090604053730.csv to table

csv file: 20090605012707.csv
FileIdentification: ./Geolife_Trajectories_1.3/data/000/Trajectory/20090605012707.csv

,Order,Latitude,Longitude,Unused,Altitude,Days,Date,Time,User
0,0,39.984683,116.318450,0,492.000000,39744.120255,2008-10-23,02:53:10,000
1,1,39.984686,116.318417,0,492.000000,39744.120313,2008-10-23,02:53:15,000
2,2,39.984688,116.318385,0,492.000000,39744.120370,2008-10-23,02:53:20,000
3,3,39.984655,116.318263,0,492.000000,39744.120428,2008-10-23,02:53:25,000
4,4,39.984611,116.318026,0,493.000000,39744.120486,2008-10-23,02:53:30,000
...,...,...,...,...,...,...,...,...,...
632921,2451,39.980755,116.329306,0,406.704350,40097.915243,2009-10-11,21:57:57,121
632922,2452,39.980814,116.329182,0,407.037434,40097.915301,2009-10-11,21:58:02,121
632923,2453,39.980723,116.329096,0,407.465486,40097.915359,2009-10-11,21:58:07,121
632924,2454,39.980412,116.329317,0,408.144649,40097.915417,2009-10-11,21:58:12,121
632925,2455,39.980230,116.329482,0,407.325866,40097.915475,2009-10-11,21:58:17,121

### Task 4 Questions and Problems

#### Output Understanding:

4.1. Was the Column User added correctly?

Yes, The Column User appears in the dataframe.
______________________________

#### Concept Understanding

4.2 Why is a User column added?

For tracking User data individually within a dataframe
______________________________


4.3 Can you delete a column from the table? If so how? 

Yes, drop()" method will delete a column when columnName is specified as string parameter ( EX: pd.drop('ColumnName') )
______________________________

#### Code Understanding: 

4.4 What panda operator was used?

There is two being used first read_csv() in the readDataFromDirectory() defintion and  second concat() to add dataframes together.
______________________________

#### Apply in typical situations:

4.5 Write a code that will let you load Points_All3 into a csv file.
* Next, check to see if Points_All3 was saved as csv file.

In [22]:
# Upload Points_M1
Points_All3.to_csv('Points_All3', index=False) #saves file as csv to the current working directory

In [23]:
# Check if  Points_M1 saved as csv file
Points_All3 = pd.read_csv('Points_All3')
Points_All3

,Order,Latitude,Longitude,Unused,Altitude,Days,Date,Time,User
0,0,39.984683,116.318450,0,492.000000,39744.120255,2008-10-23,02:53:10,0
1,1,39.984686,116.318417,0,492.000000,39744.120313,2008-10-23,02:53:15,0
2,2,39.984688,116.318385,0,492.000000,39744.120370,2008-10-23,02:53:20,0
3,3,39.984655,116.318263,0,492.000000,39744.120428,2008-10-23,02:53:25,0
4,4,39.984611,116.318026,0,493.000000,39744.120486,2008-10-23,02:53:30,0
...,...,...,...,...,...,...,...,...,...
632921,2451,39.980755,116.329306,0,406.704350,40097.915243,2009-10-11,21:57:57,121
632922,2452,39.980814,116.329182,0,407.037434,40097.915301,2009-10-11,21:58:02,121
632923,2453,39.980723,116.329096,0,407.465486,40097.915359,2009-10-11,21:58:07,121
632924,2454,39.980412,116.329317,0,408.144649,40097.915417,2009-10-11,21:58:12,121
632925,2455,39.980230,116.329482,0,407.325866,40097.915475,2009-10-11,21:58:17,121